language: python
python:
  - "3.6"

before_install:
  - export BOTO_CONFIG=/dev/null

env:
  - AWS_DEFAULT_REGION=us-east-1

install:
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt

script: python -m unittest discover -s tests/ -p "*.py" 
